---
# Install AWS FSx for Lustre client software, and mount {{ lustre_dna_name }} to /mnt/shared
- name: "pin AMI's kernel version"
  # Pin kernel version to the one baked into AMI, because AWS publish Lustre client debs for
  # certain kernel versions only. (Make sure this applies before any general apt upgrade)
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - linux-aws
    - linux-headers-aws
    - linux-image-aws
- name: AWS FSx Lustre apt key
  apt_key:
    url: https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-ubuntu-public-key.asc
- name: AWS FSx Lustre apt repo
  apt_repository:
    repo: deb https://fsx-lustre-client-repo.s3.amazonaws.com/ubuntu focal main
- name: AWS FSx Lustre client modules
  shell: apt-get install -y lustre-client-modules-$(uname -r) && modprobe lustre  # noqa 303
  changed_when: False
- name: AWS FSx Lustre mount /mnt/shared
  shell:
    cmd: |
      set -euxo pipefail
      mkdir -p /mnt/shared
      if ! grep /mnt/shared /etc/fstab; then
        echo "{{ lustre_dns_name }}@tcp:/fsx /mnt/shared lustre defaults,noatime,flock,_netdev 0 0" >> /etc/fstab
        mount --all
      fi
      touch /mnt/shared/.fsx
    executable: /bin/bash
    creates: /mnt/shared/.fsx
- name: fsx_to_s3
  # install helper script for writing files back to S3
  copy:
    src: fsx_to_s3
    dest: /usr/local/bin/fsx_to_s3
    owner: root
    group: root
    mode: 0775
- name: /mnt/shared/.s3_export_path
  # fsx_to_s3 uses this to figure out the uploaded S3 paths
  copy:
    content: "{{ s3_export_path }}"
    dest: /mnt/shared/.s3_export_path
    owner: root
    group: root
    mode: 0644
