---
# shared config, packages, and wdler user (uid 1337) used by all playbooks
- name: sshd keepalive
  lineinfile: dest=/etc/ssh/sshd_config line="{{ item }}"
  loop:
    - ClientAliveInterval 60
    - ClientAliveCountMax 5
- name: apt upgrade
  apt: upgrade=full autoremove=yes
- name: apt packages
  apt:
    pkg:
      - vim
      - byobu
      - htop
      - sysstat
      - tree
      - pv
      - jq
      - ntp
      - mosh
      - dstat
      - python3-pip
      - docker.io
      - iptables-persistent
- name: PyPI packages
  pip:
    name:
      - awscli
      - gsutil
      - azure-cli
      - docker
- name: user wdler
  user:
    name: wdler
    shell: /bin/bash
    uid: 1337
    groups: docker
    comment: Wid L. Hacker
- name: wlder sudoers
  lineinfile:
    dest: /etc/sudoers.d/50-wdler
    line: wdler ALL=(ALL) NOPASSWD:ALL
    create: yes
    owner: root
    group: root
    mode: 0440
- name: wdler nofile
  pam_limits:
    domain: wdler
    limit_type: "{{ item }}"
    limit_item: nofile
    value: 1048576
  loop:
    - hard
    - soft
- name: /home/wdler/.config
  file:
    path: /home/wdler/.config
    state: directory
    owner: wdler
    group: wdler
- name: prepare /mnt/shared/runs
  file:
    path: /mnt/shared/runs
    state: directory
    owner: wdler
    group: wdler
- name: wdler TMPDIR
  lineinfile: dest=/home/wdler/.profile line="export TMPDIR=/mnt/scratch/tmp"
  become_user: wdler
  become: yes
- name: cd /mnt/shared/runs
  lineinfile: dest=/home/wdler/.profile line="cd /mnt/shared/runs"
  become_user: wdler
  become: yes
