---
- name: jump ssh key
  authorized_key: user=wdler key="{{ lookup('file', '/home/wdler/.ssh/id_rsa.pub') }}"
- name: copy /var/provision/swarm_join_token
  copy:
    dest: /root/swarm_join_token
    src: /var/provision/swarm_join_token
    owner: root
    mode: 0400
