---
# provision miniwdl swarm manager node on AWS
- hosts: all
  become: yes
  roles:
    - aws_fsx_lustre_client
- hosts: all
  become: yes
  roles:
    - miniwdl
- hosts: all
  become: yes
  roles:
    - aws_docker_config
- hosts: all
  become: yes
  roles:
    - manager
