---
# prepare a "template" instance to be snapshotted as the swarm worker AMI (runs from the manager
# node)
- hosts: all
  become: yes
  roles:
    - aws_fsx_lustre_client
- hosts: all
  become: yes
  roles:
    - common
- hosts: all
  become: yes
  roles:
    - aws_docker_config
- hosts: all
  become: yes
  roles:
    - worker_template
