---
# provision miniwdl swarm manager node on AWS
- hosts: all
  become: yes
  roles:
    - aws_fsx_lustre_client
- hosts: all
  become: yes
  roles:
    - miniwdl
- hosts: all
  become: yes
  roles:
    - aws_docker_config
- hosts: all
  become: yes
  roles:
    - manager
  tasks:
    - name: scratch-docker.sh
      shell:
        cmd: /root/scratch-docker.sh && touch /mnt/scratch/.ok
        creates: /mnt/scratch/.ok
    - name: copy miniwdl_plugin_fsx_to_s3
      copy:
        src: miniwdl_plugin_fsx_to_s3
        dest: /home/wdler/.local/
    - name: install miniwdl_plugin_fsx_to_s3
      pip:
        name: /home/wdler/.local/miniwdl_plugin_fsx_to_s3
