---
- name: scratch-docker.sh
  # Emplace script that will prepare NVMe instance store volumes and move docker storage onto them,
  # which will be far more performant and spacious compared to the EBS root volume. The script
  # needs to run on first boot of an instance; we don't invoke it here so that this role can be
  # used to prepare an AMI. The script should be invoked from a playbook or instance user-data.
  copy:
    src: scratch-docker.sh
    dest: /root/scratch-docker.sh
    owner: root
    group: root
    mode: 0700
- name: ensure dockerd has initialized iptables by running a no-op container
  docker_container:
    name: nop
    image: alpine:3
    command: date
    detach: no
    cleanup: yes
  changed_when: False
- name: block EC2 instance metadata service from docker containers
  iptables:
    chain: DOCKER-USER
    destination: 169.254.169.254
    jump: REJECT
    action: insert
- name: block Swarm and Lustre VPC ports from docker containers
  iptables:
    chain: DOCKER-USER
    protocol: "{{ item.protocol }}"
    destination: 10.0.0.0/16
    destination_port: "{{ item.port }}"
    jump: REJECT
    action: insert
  loop:
    - { protocol: "tcp", port: "2376:2377" }
    - { protocol: "tcp", port: "7946" }
    - { protocol: "udp", port: "7946" }
    - { protocol: "tcp", port: "988" }
    - { protocol: "tcp", port: "1021:1023" }
- name: netfilter-persistent save
  command: netfilter-persistent save
  changed_when: False
- name: verify EC2 instance metadata service is blocked from docker containers
  command: docker run --rm -it alpine:3 wget -qO - http://169.254.169.254
  register: checkblock
  failed_when: checkblock.rc == 0
  changed_when: False
